vim.opt.filetype       = 'on' 
vim.opt.number         = true
vim.opt.relativenumber = true
vim.opt.tabstop        = 4
vim.opt.softtabstop    = 4
vim.opt.shiftwidth     = 4
vim.opt.expandtab      = true
vim.opt.smartindent    = true
vim.opt.confirm        = true
vim.opt.autoindent     = true
vim.opt.autoread       = true
vim.opt.smarttab       = true
vim.opt.wrap           = true
vim.opt.lazyredraw     = false
vim.opt.timeoutlen     = 600
vim.opt.swapfile       = false
vim.opt.backup         = false
vim.opt.undodir        = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile       = true
vim.opt.hlsearch       = true -- Reminder, <c-l> redraws and removes
vim.opt.incsearch      = true
vim.opt.ignorecase     = true
vim.opt.splitbelow     = true
vim.opt.splitright     = true
vim.opt.cursorline     = true
vim.opt.smartcase      = true
vim.opt.termguicolors  = true
vim.opt.scrolloff      = 4
vim.opt.signcolumn     = "yes"
vim.opt.updatetime     = 69
vim.opt.colorcolumn    = "120"
vim.opt.completeopt    = 'menu,menuone,preview,noselect,noinsert'

vim.opt.isfname:append("@-@")
